version: "3.7"

services:
  postgres:
    image: postgres
    ports:
      - 5432:4321
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  pgdata:
